/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfessionalsRouteImport } from './routes/_authenticated/professionals'
import { Route as AuthenticatedOperatorsRouteImport } from './routes/_authenticated/operators'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedImpressoesRouteImport } from './routes/_authenticated/impressoes'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedDumpIndexRouteImport } from './routes/_authenticated/dump/index'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates/$templateId'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports/$reportId'
import { Route as AuthenticatedAssessmentsAssessmentIdRouteImport } from './routes/_authenticated/assessments/$assessmentId'
import { Route as ApiPublicDumpIndexRouteImport } from './routes/api/public/dump/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksCobrancaPendenciasRouteImport } from './routes/api/public/hooks/cobranca-pendencias'
import { Route as AuthenticatedReportsReportIdPrintRouteImport } from './routes/_authenticated/reports/$reportId.print'
import { Route as AuthenticatedPatientsPatientIdGradeRouteImport } from './routes/_authenticated/patients.$patientId.grade'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfessionalsRoute =
  AuthenticatedProfessionalsRouteImport.update({
    id: '/professionals',
    path: '/professionals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperatorsRoute = AuthenticatedOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpressoesRoute = AuthenticatedImpressoesRouteImport.update({
  id: '/impressoes',
  path: '/impressoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDumpIndexRoute = AuthenticatedDumpIndexRouteImport.update({
  id: '/dump/',
  path: '/dump/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AuthenticatedTemplatesRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedAssessmentsAssessmentIdRoute =
  AuthenticatedAssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const ApiPublicDumpIndexRoute = ApiPublicDumpIndexRouteImport.update({
  id: '/api/public/dump/',
  path: '/api/public/dump/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCobrancaPendenciasRoute =
  ApiPublicHooksCobrancaPendenciasRouteImport.update({
    id: '/api/public/hooks/cobranca-pendencias',
    path: '/api/public/hooks/cobranca-pendencias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsReportIdPrintRoute =
  AuthenticatedReportsReportIdPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AuthenticatedReportsReportIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdGradeRoute =
  AuthenticatedPatientsPatientIdGradeRouteImport.update({
    id: '/patients/$patientId/grade',
    path: '/patients/$patientId/grade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/impressoes': typeof AuthenticatedImpressoesRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/professionals': typeof AuthenticatedProfessionalsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/units': typeof AuthenticatedUnitsRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRouteWithChildren
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/dump/': typeof AuthenticatedDumpIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/patients/$patientId/grade': typeof AuthenticatedPatientsPatientIdGradeRoute
  '/reports/$reportId/print': typeof AuthenticatedReportsReportIdPrintRoute
  '/api/public/hooks/cobranca-pendencias': typeof ApiPublicHooksCobrancaPendenciasRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/dump/': typeof ApiPublicDumpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/impressoes': typeof AuthenticatedImpressoesRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/professionals': typeof AuthenticatedProfessionalsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/units': typeof AuthenticatedUnitsRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRouteWithChildren
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/dump': typeof AuthenticatedDumpIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/patients/$patientId/grade': typeof AuthenticatedPatientsPatientIdGradeRoute
  '/reports/$reportId/print': typeof AuthenticatedReportsReportIdPrintRoute
  '/api/public/hooks/cobranca-pendencias': typeof ApiPublicHooksCobrancaPendenciasRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/dump': typeof ApiPublicDumpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/impressoes': typeof AuthenticatedImpressoesRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/operators': typeof AuthenticatedOperatorsRoute
  '/_authenticated/professionals': typeof AuthenticatedProfessionalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/templates': typeof AuthenticatedTemplatesRouteWithChildren
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRouteWithChildren
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/_authenticated/dump/': typeof AuthenticatedDumpIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/patients/$patientId/grade': typeof AuthenticatedPatientsPatientIdGradeRoute
  '/_authenticated/reports/$reportId/print': typeof AuthenticatedReportsReportIdPrintRoute
  '/api/public/hooks/cobranca-pendencias': typeof ApiPublicHooksCobrancaPendenciasRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/dump/': typeof ApiPublicDumpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definir-senha'
    | '/login'
    | '/announcements'
    | '/assessments'
    | '/dashboard'
    | '/goals'
    | '/impressoes'
    | '/meu-perfil'
    | '/operators'
    | '/professionals'
    | '/reports'
    | '/templates'
    | '/units'
    | '/usuarios'
    | '/assessments/$assessmentId'
    | '/reports/$reportId'
    | '/templates/$templateId'
    | '/dump/'
    | '/patients/'
    | '/patients/$patientId/grade'
    | '/reports/$reportId/print'
    | '/api/public/hooks/cobranca-pendencias'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/dump/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definir-senha'
    | '/login'
    | '/announcements'
    | '/assessments'
    | '/dashboard'
    | '/goals'
    | '/impressoes'
    | '/meu-perfil'
    | '/operators'
    | '/professionals'
    | '/reports'
    | '/templates'
    | '/units'
    | '/usuarios'
    | '/assessments/$assessmentId'
    | '/reports/$reportId'
    | '/templates/$templateId'
    | '/dump'
    | '/patients'
    | '/patients/$patientId/grade'
    | '/reports/$reportId/print'
    | '/api/public/hooks/cobranca-pendencias'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/dump'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/definir-senha'
    | '/login'
    | '/_authenticated/announcements'
    | '/_authenticated/assessments'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/impressoes'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/operators'
    | '/_authenticated/professionals'
    | '/_authenticated/reports'
    | '/_authenticated/templates'
    | '/_authenticated/units'
    | '/_authenticated/usuarios'
    | '/_authenticated/assessments/$assessmentId'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/templates/$templateId'
    | '/_authenticated/dump/'
    | '/_authenticated/patients/'
    | '/_authenticated/patients/$patientId/grade'
    | '/_authenticated/reports/$reportId/print'
    | '/api/public/hooks/cobranca-pendencias'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/dump/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  LoginRoute: typeof LoginRoute
  ApiPublicHooksCobrancaPendenciasRoute: typeof ApiPublicHooksCobrancaPendenciasRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicDumpIndexRoute: typeof ApiPublicDumpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/professionals': {
      id: '/_authenticated/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof AuthenticatedProfessionalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operators': {
      id: '/_authenticated/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthenticatedOperatorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impressoes': {
      id: '/_authenticated/impressoes'
      path: '/impressoes'
      fullPath: '/impressoes'
      preLoaderRoute: typeof AuthenticatedImpressoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dump/': {
      id: '/_authenticated/dump/'
      path: '/dump'
      fullPath: '/dump/'
      preLoaderRoute: typeof AuthenticatedDumpIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedTemplatesRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/assessments/$assessmentId': {
      id: '/_authenticated/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/api/public/dump/': {
      id: '/api/public/dump/'
      path: '/api/public/dump'
      fullPath: '/api/public/dump/'
      preLoaderRoute: typeof ApiPublicDumpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cobranca-pendencias': {
      id: '/api/public/hooks/cobranca-pendencias'
      path: '/api/public/hooks/cobranca-pendencias'
      fullPath: '/api/public/hooks/cobranca-pendencias'
      preLoaderRoute: typeof ApiPublicHooksCobrancaPendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/$reportId/print': {
      id: '/_authenticated/reports/$reportId/print'
      path: '/print'
      fullPath: '/reports/$reportId/print'
      preLoaderRoute: typeof AuthenticatedReportsReportIdPrintRouteImport
      parentRoute: typeof AuthenticatedReportsReportIdRoute
    }
    '/_authenticated/patients/$patientId/grade': {
      id: '/_authenticated/patients/$patientId/grade'
      path: '/patients/$patientId/grade'
      fullPath: '/patients/$patientId/grade'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdGradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAssessmentsRouteChildren {
  AuthenticatedAssessmentsAssessmentIdRoute: typeof AuthenticatedAssessmentsAssessmentIdRoute
}

const AuthenticatedAssessmentsRouteChildren: AuthenticatedAssessmentsRouteChildren =
  {
    AuthenticatedAssessmentsAssessmentIdRoute:
      AuthenticatedAssessmentsAssessmentIdRoute,
  }

const AuthenticatedAssessmentsRouteWithChildren =
  AuthenticatedAssessmentsRoute._addFileChildren(
    AuthenticatedAssessmentsRouteChildren,
  )

interface AuthenticatedReportsReportIdRouteChildren {
  AuthenticatedReportsReportIdPrintRoute: typeof AuthenticatedReportsReportIdPrintRoute
}

const AuthenticatedReportsReportIdRouteChildren: AuthenticatedReportsReportIdRouteChildren =
  {
    AuthenticatedReportsReportIdPrintRoute:
      AuthenticatedReportsReportIdPrintRoute,
  }

const AuthenticatedReportsReportIdRouteWithChildren =
  AuthenticatedReportsReportIdRoute._addFileChildren(
    AuthenticatedReportsReportIdRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRouteWithChildren
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsReportIdRoute:
    AuthenticatedReportsReportIdRouteWithChildren,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedTemplatesRouteChildren {
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
}

const AuthenticatedTemplatesRouteChildren: AuthenticatedTemplatesRouteChildren =
  {
    AuthenticatedTemplatesTemplateIdRoute:
      AuthenticatedTemplatesTemplateIdRoute,
  }

const AuthenticatedTemplatesRouteWithChildren =
  AuthenticatedTemplatesRoute._addFileChildren(
    AuthenticatedTemplatesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedImpressoesRoute: typeof AuthenticatedImpressoesRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedOperatorsRoute: typeof AuthenticatedOperatorsRoute
  AuthenticatedProfessionalsRoute: typeof AuthenticatedProfessionalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRouteWithChildren
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedDumpIndexRoute: typeof AuthenticatedDumpIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedPatientsPatientIdGradeRoute: typeof AuthenticatedPatientsPatientIdGradeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedImpressoesRoute: AuthenticatedImpressoesRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedOperatorsRoute: AuthenticatedOperatorsRoute,
  AuthenticatedProfessionalsRoute: AuthenticatedProfessionalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRouteWithChildren,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedDumpIndexRoute: AuthenticatedDumpIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedPatientsPatientIdGradeRoute:
    AuthenticatedPatientsPatientIdGradeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DefinirSenhaRoute: DefinirSenhaRoute,
  LoginRoute: LoginRoute,
  ApiPublicHooksCobrancaPendenciasRoute: ApiPublicHooksCobrancaPendenciasRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicDumpIndexRoute: ApiPublicDumpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
